spring.application.name=game-engine
management.endpoints.web.exposure.exclude=health,info
management.endpoints.web.exposure.include=*
management.info.env.enabled=true
info.app.name=game-engine

coach.name = mickey
team.name = mouse club

#change server port

server.port=7070

#application context path

#server.servlet.context-path=/game-enginei

# Enable the H2 console interface
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configure the in-memory database properties
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# This saves the database as a file named 'devdb' inside your project folder
spring.datasource.url=jdbc:h2:file:./data/devdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Keeps the database alive and updating automatically
spring.jpa.hibernate.ddl-auto=update