spring.application.name=game-engine
management.endpoints.web.exposure.exclude=health,info
management.endpoints.web.exposure.include=*
management.info.env.enabled=true
info.app.name=game-engine

coach.name = mickey
team.name = mouse club

#change server port

server.port=7070

#application context path

#server.servlet.context-path=/game-enginei